### ISSUE TITLE
Error: npm install

### ISSUE THREAD

**Issue by kooy** [ruffchain/Shepherd#6]
npm install

...
```
> blockchain-sdk@1.1.0 build /Users/one/Shepherd/node_modules/blockchain-sdk
> gulp build

[10:01:12] Using gulpfile ~/Shepherd/node_modules/blockchain-sdk/gulpfile.js
[10:01:12] Starting 'compile'...
[10:01:12] Starting 'res'...
[10:01:12] Finished 'res' after 4.47 ms
src/client/lib/unhandled_rejection.ts(7,73): error TS2533: Object is possibly 'null' or 'undefined'.
src/client/lib/unhandled_rejection.ts(7,80): error TS2339: Property 'stack' does not exist on type '{}'.
src/client/lib/unhandled_rejection.ts(8,74): error TS2533: Object is possibly 'null' or 'undefined'.
src/client/lib/unhandled_rejection.ts(8,81): error TS2339: Property 'stack' does not exist on type '{}'.
TypeScript: 4 semantic errors
TypeScript: emit succeeded (with errors)
[10:01:16] Finished 'compile' after 4.53 s
[10:01:16] Starting 'build'...
[10:01:16] Finished 'build' after 36 μs
added 554 packages in 224.118s
```

-------------------------------------------

npm run build

```
> shepherd@0.1.0 build /Users/one/Shepherd
> gulp build

[10:03:29] Using gulpfile ~/Shepherd/gulpfile.js
[10:03:29] Starting 'build'...
[10:03:29] Starting 'clean'...
[10:03:29] Finished 'clean' after 8.87 ms
[10:03:29] Starting 'compile'...
programs/node/chain/handler.ts(1,123): error TS2305: Module '"/Users/one/Shepherd/node_modules/blockchain-sdk/dist/blockchain-sdk/src/client/index"' has no exported member 'MapToObject'.
programs/node/chain/handler.ts(202,30): error TS2339: Property 'getMiners' does not exist on type 'DposViewContext'.
TypeScript: 2 semantic errors
TypeScript: emit succeeded (with errors)
[10:03:30] 'compile' errored after 1.5 s
[10:03:30] Error: TypeScript: Compilation failed
    at Output.mightFinish (/Users/one/Shepherd/node_modules/gulp-typescript/release/output.js:130:43)
    at applySourceMap.then.appliedSourceMap (/Users/one/Shepherd/node_modules/gulp-typescript/release/output.js:43:22)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[10:03:30] 'build' errored after 1.51 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shepherd@0.1.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shepherd@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/one/.npm/_logs/2019-10-02T02_03_30_620Z-debug.log
```

**Comment by topelinux** [comment]
Please use ChainNode project
